import type { Metadata } from "next";
import "./globals.css";
import { fjalla, libre, workSans } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${workSans.variable} ${fjalla.variable} ${libre.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
